# Generated by Django 3.1.5 on 2021-02-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210201_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position_broker', to='core.broker'),
        ),
    ]
