# Generated by Django 3.1.5 on 2021-02-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210201_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position_asset', to='core.asset'),
        ),
    ]
