# Generated by Django 3.1.6 on 2021-03-23 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210201_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='broker_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.broker'),
        ),
        migrations.AlterField(
            model_name='account',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
