# Generated by Django 3.1.6 on 2021-04-21 19:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210323_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='broker_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300)),
        ),
        migrations.AlterField(
            model_name='account',
            name='token_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300)),
        ),
        migrations.AlterField(
            model_name='account',
            name='token_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300)),
        ),
        migrations.AlterField(
            model_name='investor',
            name='profile_picture',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
